### ISSUE TITLE
Conversion of DotMap() object to OrderedDict

### ISSUE THREAD

**Issue by jtlz2** [drgrib/dotmap#75]
`dotmap` is awesome for which huge thanks.

`DotMap()` has a `toDict()` method. How an I convert a `DotMap()` to an `OrderedDict` rather?

Thanks again

**Comment by drgrib** [comment]
Glad you are enjoying it. A `DotMap` is a subclass of `OrderedDict`, so it can be cast to one directly:

``` python
from dotmap import DotMap
from collections import OrderedDict

m = DotMap()
m.a = 1
m.b = 2

o = OrderedDict(m)

print(m)
print(o)
```

```

**Comment by drgrib** [comment]
Glad you are enjoying it. A `DotMap` is a subclass of `OrderedDict`, so it can be cast to one directly:

``` python
from dotmap import DotMap
from collections import OrderedDict

m = DotMap()
m.a = 1
m.b = 2

o = OrderedDict(m)

print(m)
print(o)
```

```
DotMap(a=1, b=2)
OrderedDict([('a', 1), ('b', 2)])
```

**Comment by jtlz2** [comment]
But this is wonderful news - did I miss that in the docs? Thanks again!

**Comment by drgrib** [comment]
Happy to hear that :) You didn't miss anything no. This isn't documented because it isn't a use case I ever anticipated someone needing. The `DotMap` itself performs the only function I personally have ever needed from an `OrderedDict`: iteration ordered by assignment. I didn't ask because I didn't think it was relevant to answering your question, but why would you need to do this?
