### ISSUE TITLE
DotMap contains key-value pair 'shape': DotMap()

### ISSUE THREAD

**Issue by aabmets** [drgrib/dotmap#95]
By the documentation, DotMap should not contain this key-value pair.
I need to specifically remove it manually after toDict() to prevent errors in my code.
Either clarify the documentation that this key-value pair is automatically added or make the field private.

**Comment by drgrib** [comment]
I don't see what you are talking about. `shape` is not present by default in `DotMap` in my test run on the latest version. It is an empty `DotMap`, as documented:

``` python
from dotmap import DotMap
m = DotMap()
print(m.shape)
```
```
DotMap()
```

If you want to turn off dynamic child generation on access, you need to init the `DotMap` with `DotMap(_dynamic=False)` (also documented):
``` python
from dotmap import DotMap
m = DotMap(_dynamic=False)
print(m.shape)
``` 
```
<stack trace>
...
AttributeError: 'DotMap' object has no attribute 'shape'
```

**Comment by DesktopMan** [comment]
I'm having the exact same issue. It only occurs during debugging if:

- You step the creation of the DotMap
- You stop at a breakpoint after the DotMap has been created

It seems stopping at a breakpoint directly changes the DotMap. In the image below you can see this occur in a very simple script. Editor: PyCharm 2024.1.3, Python: 3.12.4, dotmap: 1.3.30

![image](https://github.com/user-attachments/assets/6baa2ce6-6dd0-4ce8-8add-929144e76de8)

This seems to be because PyCharm accesses __get_attr__ on objects, which in this case results in the creation of the shape key.
https://youtrack.jetbrains.com/issue/PY-48306/PyCharm-Debugger-accesses-shape-object-attribute-with-overriden-getattr-method
